### ISSUE TITLE
Add focus judgment

### ISSUE THREAD

**Issue by tenSunFree** [nikhilbadyal/keepnotes#4]
Maybe consider first judging whether there is focus, if there is focus, cancel the focus and save the data, and inform the user.
If there is no focus, go back directly to the previous page.
The user experience may be better.
https://user-images.githubusercontent.com/23090085/163681765-33802b2b-9133-4aa3-a1c5-64f138110cf5.mp4

part of the code, maybe you can try to adjust it like this.
<img width="468" alt="2022-04-16_234417" src="https://user-images.githubusercontent.com/23090085/163681880-2c87b4cd-8c0e-44fd-ae25-d99519a41b1d.png">

**Comment by nikhilbadyal** [comment]
**Great**, will look into this.

**Comment by nikhilbadyal** [comment]
I looked into this. I liked the idea of checking the focus first. But `return false` is probably not a good idea. It increases the click count. No. of the times the user needs to press the back button to reach home will be 2 and I don't want users to exercise their fingers. I surely can do the `save pop-up` thing.

**Comment by nikhilbadyal** [comment]
[Done](https://github.com/nikhilbadyal/keepnotes/commit/5ff9eba73f5a936e78e0c0c11a615b9cfcab47d9)
